name: Docs Build
# This workflow compiles the LaTeX documents in the docs directory whenever changes 
#are pushed to the main branch or when a pull request is opened targeting the main branch
#but only if the changes affect files in the docs directory or this workflow file itself.
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs-build.yml"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/docs-build.yml"
permissions:
  contents: write
  
jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile report LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report.tex
          working_directory: docs/LaTeX
      
      - name: Update PDF in repository
        run: |
          git config user.name "[GitHub Actions]LaTeX Builder Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mv docs/LaTeX/report.pdf docs/report.pdf
          git add docs/report.pdf
          git commit -m "Update compiled PDF documents" || echo "No changes to commit"
          git push origin main